import Head from 'next/head';

export default function SEO() {
    return (
        <Head>
            <title>Sigma Pi Portal</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}